### ISSUE TITLE
tsb instruction might not work, per 65C02_extended_opcodes_test.bin

### ISSUE THREAD

**Issue by heistp** [beevik/go6502#1]
Hi, just noting that I ran 65C02_extended_opcodes_test.bin, from here:

https://github.com/Klaus2m5/6502_65C02_functional_tests/tree/master/bin_files

as follows:

```
load 65C02_extended_opcodes_test.bin $0000
run $0400
```

and an infinite loop occurs at an address that might mean the tsb instruction didn't work:

```
* run $0400
Running from $0400. Press ctrl-C to break.
^C
0733-   4C 33 07    JMP   $0733     A=33 X=11 Y=22 PS=[------] SP=FF PC=0733 C=141330056
```

6502_functional_test.bin did run successfully, so take this for what it's worth. :)

**Comment by beevik** [comment]
Thanks for doing this!  (And sorry for the late response.)

I am definitely going to check this out.

**Comment by beevik** [comment]
It appears the compiled version of the 65c02 test (the `6502_functional_test.bin` file) expects the Rockwell and WDC 65c02 instructions to be implemented. Unfortunately, I did not implement these.  Shouldn't be too difficult to add them though.  I'll add it to my list.

**Comment by heistp** [comment]
Sounds good. At some point I came across this project with a friend who's into 65c02 programming. We were trying these functional tests on different emulators for fun, and since I like Go this one was interesting to me. Keep up the good work. :)

**Comment by chromi** [comment]
As it happens, TSB and TRB are not specific to the Rockwell/WDC versions of the 65C02, but should be present in all CMOS versions of the 6502, including the CMD 65SC02 and the 65816 (which uses the Rockwell opcodes for other things).

**Comment by beevik** [comment]
@chromi This simulator implements the TSB and TRB instructions, but it's missing the BBR and BBS instructions, which were the ones causing the test in question to fail.

**Comment by beevik** [comment]
Closing this issue due to its age.
